trigger:
- main  # Trigger pipeline on changes to the 'main' branch

pool:
  name: 'default'

stages:
- stage: PullChanges
  displayName: 'Pull Latest Changes from Repo'
  jobs:
  - job: PullRepo
    displayName: 'Pull Repository'
    pool:
      name: default
    steps:
    - script: |
        echo "Pulling latest changes from repository..."
        cd /home/amanar/myagent/nginx/ && git pull origin master
      displayName: 'Pull Changes from Repo'

- stage: MoveConfig
  displayName: 'Move Configuration to Nginx Path'
  jobs:
  - job: MoveNginxConfig
    displayName: 'Move Nginx Configuration'
    pool:
      name: default
    steps:
    - script: |
        echo "Moving Nginx default configuration..."
        sudo mv /home/amanar/myagent/nginx/default /etc/nginx/sites-enabled/default
      displayName: 'Move Default Configuration to Nginx Path'

- stage: TestAndReloadNginx
  displayName: 'Test and Reload Nginx'
  jobs:
  - job: TestReloadNginx
    displayName: 'Test and Reload Nginx Service'
    pool:
      name: default
    steps:
    - script: |
        echo "Testing Nginx configuration..."
        nginx -t
      displayName: 'Test Nginx Configuration'
    - script: |
        echo "Reloading Nginx service..."
        sudo systemctl reload nginx
      displayName: 'Reload Nginx Service'

