trigger:
- main  # Trigger pipeline on changes to the 'main' branch

pool:
  name: 'default'

stages:
- stage: Deploy
  jobs:
  - deployment: DeployToVM
    displayName: 'Deploy to VM'
    pool:
      name: default # Change this to your agent pool name
    environment:
      name: 'Hetzner' # Replace with your Azure DevOps environment name
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying to Nginx server..."
              mv default /etc/nginx/sites-enabled/default
#              ssh root@65.108.152.20 'sudo systemctl restart nginx'
            displayName: 'Copy Files to Server and Restart Nginx'
